name: 'hailing_project'
version: '1.0.0'
config-version: 2

profile: 'hailing_project'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# models:
#   dbt_project:
#     +persist_docs:
#       relation: true
#       columns: true
#     # Config indicated by + and applies to all files under models/example/
#     example:
#       +materialized: view

models:

  hailing_project: # samain kaya nama dbt_project, bukan folder

    staging:
      +materialized: view
      +schema: rizky_dwh_hailing_staging
      +persists_docs:
        relation: true
        columns: true
      tag: group_1


    facts:
      +materialized: view
      +schema: rizky_dwh_hailing_facts
      +persists_docs:
        relation: true
        columns: true
      tag: group_2
      
    marts:
      +materialized: view
      +schema: rizky_dwh_hailing_marts
      +persists_docs:
        relation: true
        columns: true
      tag: group_3
      
      

