version: '3.8'

services:
  dbt:
    build: .
    container_name: dbt_hailing
    volumes:
      - ./:/usr/app
      - ../airflow_app/credentials.json:/root/.dbt/credentials.json  # Mount credentials.json from airflow_app
    working_dir: /usr/app/
    environment:
      DBT_PROFILES_DIR: /usr/app/
    entrypoint: ["tail", "-f", "/dev/null"]